#execution_env=local
execution_env=remote


appURL1=http://54.227.28.143/Login?c=TMS

#appURL2=https://tutorialsninja.com/demo/
username=Admin
pwd=logixerp
#password=test@12345
#searchProductName=iPhone